### ISSUE TITLE
3주차 스터디

### ISSUE THREAD

**Issue by hyorin03** [hhi-5258/android-study#3]
학습목표
---
- Ch.3 액티비티 생명주기

마감기한
---
6월 5일 토요일 21시 까지

**Comment by hyorin03** [comment]
https://lin9703.github.io/2021-06-04/Android_Programming_Ch_3

**Comment by hhi-5258** [comment]
https://velog.io/@hhi-5258/%EB%A9%B4%EC%A0%91-%EB%8C%80%EB%B9%84-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EA%B8%B0%EC%B4%88
