### ISSUE TITLE
4주차 스터디

### ISSUE THREAD

**Issue by hyorin03** [hhi-5258/android-study#4]
학습목표
---
- Ch.4 UI 상태 유지하기 

마감기한
---
6월 12일 토요일 21시 까지

**Comment by hyorin03** [comment]
https://lin9703.github.io/2021-06-07/Android_Programming_Ch_4

**Comment by hhi-5258** [comment]
https://velog.io/@hhi-5258/SIS-vs-AAC-ViewModel-vs-LiveData
